language: R
sudo: false
cache: packages

env:
  global:
    secure: RaVmaQjDIcbsEZmgfhA52iTnbaq7vU14NVz7q2lS0Pl8baT7aT9UGePTqjhJ4I4kTE0Q2SL9JpK8+zHpuiNnApXGU/gzr11hGnLGRGkc48c5E6i70F7YM1NfClAsey35Vqp2VZpSytEtj4lka7oyAN5gWE+i9DT2uNeRuY8Gy8HCJkDuO82z13R+9StcEhEN356PE9IpqI67UwUKCiizlpzSTQdi02e0hDxdeCWXrWtJeY1bcVYGyGvKUdlbxAC8x/eqmqH0KmIlDCE/JY3KhPDnYF124hprVoAm5vBdX9eQ5q/79ce5xQab7IFSWRNeHIcanHQm/6zLNZgMXrFwoR3JnhIqX0gz9H4bg92Ai/kL5G9PmrlywUZ9roGj7EBc4be4uVnsUzcDMFbvxnLxAuVdrt1w3Jhk5WwIRNUO7L+h5WB7FIU4U9LHXl4wOtktwGvidvgZ9sgpYnPnvlqIYW5e1xvsx3KdZDSl6zLVe1jYp07WQFZf36tzubpifOWMwamx/cQO85gLo5RPIRpxO2qFChTkNZvgWE/29yQgx64KMnSEeH/fV8REBm6Xc82eMPCSYJVkTtGpN+VgnyINpnRnHDj+YsX4Il7v+7KljIN9WxgHm2xbvpK7mMHIkudN/L/UXqN99bDuXSEZikBbyak3u0jl0ZFRBUlnH9usjhI=

before_script:
- PACKAGE=`awk '/^Package\:/ { print $2 }' DESCRIPTION`
- VERSION=`awk '/^Version\:/ { print $2 }' DESCRIPTION`
- PKG_TARBALL=${PACKAGE}_${VERSION}.tar.gz

script:
- R CMD build .
- R CMD check ${PKG_TARBALL} --as-cran --no-manual
- R CMD INSTALL ${PKG_TARBALL}
- Rscript -e "pkgdown::build_site()"

deploy:
  provider: pages
  skip_cleanup: true
  on:
    branch: master
  local_dir: docs
  github_token: "$GITHUB_TOKEN"

notifications:
  email: false
  slack:
    secure: cG13GUz4C3szTL//TL/vvq+3jyPPkQWYNauf9V2JkpDkoH1JxGl0nhi/gnX0okMKZX7ojSWsziOjayj6P7TEIasCc6gxx/EmdFvs5VHZMNj0kfb1GN9XSrNvZgB3h5qKvWtos/oiuhONKlcNGLocL0n01jTc2sYo1O0WKNo7FI5N9Ia/9d1DPTMIGJ7cORCyZwIIo6aaoB8QsnHzzFzqPRtgLatiiAPeqgi2aueVghSgxAWRNbOvPBVZJde3/iqhVTKhjD9EFg5Po8Yr9vjP4sWJTmcbHFMITRm1yZaVLkXAHKrsfseksLad6AaZY8TxbOmho2YKNefnYbFuyOkUOLrReM4ZxP6PQOHQN3h9eI/V2sRSZj94nsXDfwEWFdNRVJHlgp0uta1t6Ppdx5wIeSeaM89ntKPRloiZQvSNnrrf4fHPlbdDO1EdHIZTwRmcm9ngoEG7q66/uWo+ROm1yuBi40R3TiTNKqrQWs4YpYJBQkhoakD5BlyurKtKm+jnzSjjnz/U0KOzy4U8Ia6vkPHfrXXY4SJs5VsXZZx5YOWLMb88xZObMdGspRnY59XnRHY28clTnPLxfpMpITY4Z6e6cbZxb+Uki4c1bfgKifO6alHAhqthE01NvQTGBIzndfQQ1XXbHLvK5XSj1y33F5yb7ikPaIRwRSsqnhjwlBQ=
