---
title: "Adjacency Matrix"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Adjacency Matrix}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load packages

```{r load-packages, warning=FALSE, message=FALSE}
library(tidyverse)
library(rebeltrack)
```

### Load Dataset

```{r load-dataset, eval=TRUE}
dataset <- rebeltrack_load_dataset(type = UCDP_STATE_BASED)
```

### Create RebelTrack DataFrame 

```{r create-dataframe, eval=TRUE}
data <- rebeltrack_dataframe(dataset,
                             side = SIDE_B,
                             period = "month",
                             balanced = TRUE)
data
```

### Calculate Adjacency Matrix

```{r create-adjacency-matrix, eval=TRUE}
adjacency_matrix <- rebeltrack_adjacency_matrix(data)

dim(adjacency_matrix)
```

### Apply Adjacency Matrix

```{r apply-adjacency-matrix, eval=TRUE}
data <- data %>%
  rebeltrack_event_count(event_count, weight = adjacency_matrix)

data
```



